version: "2"
services:
  client:
    image: webapp-client
    build:
      context: ./client
    restart: always
    ports:
      - "3000:3000"
    working_dir: /client/src/app
    volumes:
      - ./client:/client/src/app
    entrypoint: ["npm", "start"]
    stdin_open: true
    links:
      - api
    networks:
      - webappnetwork
  api:
    image: webapp-api
    build:
      context: ./api
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./api:/api
    depends_on:
      - mongodb
    networks:
      - webappnetwork
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - ./data-node:/data/db
    ports:
      - 27018:27018
    command: mongod --noauth
    networks:
      - webappnetwork
networks:
  webappnetwork:
    driver: bridge
